export const BACKOFF_ERROR_THRESHOLD = 5;
export const BACKOFF_429_SECONDS = 300;
export const BACKOFF_MAX_SECONDS = 3600;

export const RPM_WINDOW_SECONDS = 60;
export const RPD_WINDOW_SECONDS = 86400;

export const REQUEST_TIMEOUT_SECONDS = 25;
export const GLOBAL_TIMEOUT_MS = 28_000;
